export const stats = [
  {
    id: 1,
    label: "Total Projects",
    value: "24",
    change: "+3 this month",
    trend: "up",
    color: "violet",
    icon: "Folders",
  },
  {
    id: 2,
    label: "Active Tasks",
    value: "138",
    change: "+12 this week",
    trend: "up",
    color: "blue",
    icon: "CheckSquare",
  },
  {
    id: 3,
    label: "Team Members",
    value: "9",
    change: "2 pending invite",
    trend: "neutral",
    color: "emerald",
    icon: "Users",
  },
  {
    id: 4,
    label: "Completed",
    value: "87%",
    change: "+5% vs last month",
    trend: "up",
    color: "amber",
    icon: "TrendingUp",
  },
];

export const tasks = [
  {
    id: 1,
    title: "Design new onboarding flow",
    project: "FlowPilot Web",
    priority: "high",
    status: "in-progress",
    due: "Jul 18",
    assignee: { name: "Alex M.", color: "bg-violet-500" },
  },
  {
    id: 2,
    title: "Fix authentication token refresh bug",
    project: "Backend API",
    priority: "critical",
    status: "in-progress",
    due: "Jul 15",
    assignee: { name: "Sara K.", color: "bg-blue-500" },
  },
  {
    id: 3,
    title: "Write unit tests for dashboard components",
    project: "FlowPilot Web",
    priority: "medium",
    status: "todo",
    due: "Jul 22",
    assignee: { name: "James R.", color: "bg-emerald-500" },
  },
  {
    id: 4,
    title: "Set up CI/CD pipeline on AWS",
    project: "DevOps",
    priority: "high",
    status: "todo",
    due: "Jul 25",
    assignee: { name: "Priya N.", color: "bg-amber-500" },
  },
  {
    id: 5,
    title: "Update API documentation",
    project: "Backend API",
    priority: "low",
    status: "done",
    due: "Jul 12",
    assignee: { name: "Tom W.", color: "bg-pink-500" },
  },
  {
    id: 6,
    title: "Implement dark mode toggle",
    project: "FlowPilot Web",
    priority: "medium",
    status: "done",
    due: "Jul 10",
    assignee: { name: "Alex M.", color: "bg-violet-500" },
  },
];

export const projects = [
  {
    id: 1,
    name: "FlowPilot Web",
    description: "Main product frontend — React + Tailwind",
    progress: 68,
    status: "active",
    color: "from-violet-500 to-indigo-500",
    tasks: { total: 42, done: 28 },
    team: [
      { name: "Alex M.", color: "bg-violet-500" },
      { name: "Sara K.", color: "bg-blue-500" },
      { name: "Tom W.", color: "bg-pink-500" },
    ],
    due: "Aug 1",
  },
  {
    id: 2,
    name: "Backend API",
    description: "Express.js REST API with MongoDB",
    progress: 54,
    status: "active",
    color: "from-blue-500 to-cyan-500",
    tasks: { total: 35, done: 19 },
    team: [
      { name: "James R.", color: "bg-emerald-500" },
      { name: "Priya N.", color: "bg-amber-500" },
    ],
    due: "Aug 15",
  },
  {
    id: 3,
    name: "Mobile App",
    description: "React Native iOS & Android client",
    progress: 31,
    status: "active",
    color: "from-emerald-500 to-teal-500",
    tasks: { total: 58, done: 18 },
    team: [
      { name: "Sara K.", color: "bg-blue-500" },
      { name: "Alex M.", color: "bg-violet-500" },
      { name: "Priya N.", color: "bg-amber-500" },
    ],
    due: "Sep 10",
  },
  {
    id: 4,
    name: "DevOps & Infra",
    description: "AWS infrastructure, CI/CD, monitoring",
    progress: 82,
    status: "active",
    color: "from-amber-500 to-orange-500",
    tasks: { total: 20, done: 16 },
    team: [
      { name: "Tom W.", color: "bg-pink-500" },
      { name: "James R.", color: "bg-emerald-500" },
    ],
    due: "Jul 30",
  },
];

export const activityFeed = [
  { id: 1, user: "Sara K.", action: "completed task", target: "Fix auth token refresh", time: "2m ago", color: "bg-blue-500" },
  { id: 2, user: "Alex M.", action: "created project", target: "Mobile App v2", time: "1h ago", color: "bg-violet-500" },
  { id: 3, user: "Priya N.", action: "commented on", target: "CI/CD pipeline setup", time: "3h ago", color: "bg-amber-500" },
  { id: 4, user: "James R.", action: "moved task to", target: "In Progress", time: "5h ago", color: "bg-emerald-500" },
  { id: 5, user: "Tom W.", action: "closed issue", target: "API docs outdated", time: "Yesterday", color: "bg-pink-500" },
];
